language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=0phoff
      # Note: TWINE_PASSWORD is set in Travis settings
    - CIBW_BUILD=cp3?-*
    - CIBW_SKIP=cp33-* cp34-* cp-35*
    - CIBW_BEFORE_BUILD=cd {project}/brambox && make build cython=1 debug=0

script:
  - $PIP install cibuildwheel==0.11.1
  - cibuildwheel --output-dir wheelhouse brambox/
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi

