language: python

matrix:
  include:
    # LINUX
    - name: "Linux py3.6"
      python: 3.6
      services: docker
      env:
        - CIBW_BUILD="cp36-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.3 cython==0.28.2 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

    - name: "Linux py3.7"
      python: 3.7
      services: docker
      env:
        - CIBW_BUILD="cp37-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.14.6 cython==0.28.3 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

    - name: "Linux py3.8"
      python: 3.8
      services: docker
      env:
        - CIBW_BUILD="cp38-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.17.5 cython==0.29.14 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

    # ARMv8
    - name: "ARMv8 py3.6"
      arch: arm64
      python: 3.6
      services: docker
      env:
        - CIBW_BUILD="cp36-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.3 cython==0.28.2 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

    - name: "ARMv8 py3.7"
      arch: arm64
      python: 3.7
      services: docker
      env:
        - CIBW_BUILD="cp37-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.14.6 cython==0.28.3 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

    - name: "ARMv8 py3.8"
      arch: arm64
      python: 3.8
      services: docker
      env:
        - CIBW_BUILD="cp38-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.17.5 cython==0.29.14 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

    # MacOS
    - name: "MacOS py3.6"
      os: osx
      language: shell
      env: 
        - CIBW_BUILD="cp36-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.3 cython==0.28.2 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

    - name: "MacOS py3.7"
      os: osx
      language: shell
      env: 
        - CIBW_BUILD="cp37-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.14.6 cython==0.28.3 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

    - name: "MacOS py3.8"
      os: osx
      language: shell
      env: 
        - CIBW_BUILD="cp38-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.17.5 cython==0.29.14 && cd {package} && make build cython=1 debug=0"
        - UPLOAD_SDIST=""

env:
  global:
    - TWINE_USERNAME=0phoff

install:
  - python3 -m pip install cibuildwheel==1.5.5

script:
  - python3 -m cibuildwheel --output-dir wheelhouse brambox/
  - |
    if [[ $UPLOAD_SDIST ]]; then
      cd brambox
      python setup.py sdist
      cd ..
    fi

after_success:
  - python3 -m pip install -U twine
  - python3 -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - |
    if [[ $UPLOAD_SDIST ]]; then
      cd brambox
      python3 -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
      cd ..
    fi
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m twine upload wheelhouse/*.whl
      if [[ $UPLOAD_SDIST ]]; then
        cd brambox
        python3 -m twine upload --skip-existing dist/*.tar.gz
        cd ..
      fi
    fi

