language: python

matrix:
  include:
    - name: "Linux py3.6"
      sudo: required
      language: python
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp36-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.3 cython==0.28.2 && cd {project} && make build cython=1 debug=0"
        - UPLOAD_SDIST=1

    - name: "Linux py3.7"
      sudo: required
      language: python
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp37-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.14.6 cython==0.28.3 && cd {project} && make build cython=1 debug=0"

    - name: "MacOS py3.6"
      os: osx
      language: generic
      env: 
        - PIP=pip2
        - CIBW_BUILD="cp36-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.3 cython==0.28.2 && cd {project} && make build cython=1 debug=0"

    - name: "MacOS py3.7"
      os: osx
      language: generic
      env: 
        - PIP=pip2
        - CIBW_BUILD="cp37-*"
        - CIBW_BEFORE_BUILD="pip install numpy==1.14.6 cython==0.28.3 && cd {project} && make build cython=1 debug=0"

env:
  global:
    - TWINE_USERNAME=0phoff

script:
  # Build wheels
  - $PIP install cibuildwheel==0.11.1
  - cibuildwheel --output-dir wheelhouse brambox/

after_success:
  # Upload to PyPi
  - python -m pip install twine
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - |
    echo $UPLOAD_SDIST
    [ -z ${UPLOAD_SDIST+x} ] && python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ brambox/dist/*.tar.gz
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m twine upload wheelhouse/*.whl
      [ -z "$UPLOAD_SDIST" ] && python -m twine upload --skip-existing brambox/dist/*.tar.gz
    fi

