environment:
  TWINE_USERNAME: 0phoff

  matrix:
    - CIBW_BUILD: cp36-*
      CIBW_BEFORE_BUILD: pip install numpy==1.13.3 cython==0.28.2 && cd {project} && CYTHON=1 CFLAGS=-O3 CDEBUG=0 python setup.py build_ext --force --compiler=msvc

    - CIBW_BUILD: cp37-*
      CIBW_BEFORE_BUILD: pip install numpy==1.14.6 cython==0.28.3 && cd {project} && CYTHON=1 CFLAGS=-O3 CDEBUG=0 python setup.py build_ext --force --compiler=msvc


install:
  git submodule update --init --recursive


build_script:
  - pip install cibuildwheel==0.11.1
  - cibuildwheel --output-dir wheelhouse brambox/
  - >
    python -m pip install twine
    &&
    python -m twine upload wheelhouse/*.whl

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
